#!/usr/bin/env bash

CHANGED_PYTHON_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep ".py\$")

if [ -z "$CHANGED_PYTHON_FILES" ]
then
   echo "No Python files found. No reason to run checks."
   exit 0
fi

set -e

isort $CHANGED_PYTHON_FILES
black $CHANGED_PYTHON_FILES

git add $CHANGED_PYTHON_FILES

