"""initia migration

Revision ID: 07e8e0607ebb
Revises: 
Create Date: 2021-06-13 13:42:52.642937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e8e0607ebb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('cell', sa.String(length=32), nullable=True),
    sa.Column('nat', sa.String(length=8), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('street_number', sa.Integer(), nullable=True),
    sa.Column('street_name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('postcode', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longitude', sa.String(), nullable=True),
    sa.Column('timezone_offset', sa.String(), nullable=True),
    sa.Column('timezone_description', sa.String(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('salt', sa.String(), nullable=True),
    sa.Column('md5', sa.String(length=32), nullable=True),
    sa.Column('sha1', sa.String(length=40), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('data_of_birth', sa.String(length=32), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('registered_date', sa.String(length=32), nullable=True),
    sa.Column('registered_age', sa.SmallInteger(), nullable=True),
    sa.Column('id_name', sa.String(), nullable=True),
    sa.Column('id_value', sa.String(), nullable=True),
    sa.Column('picture_l', sa.String(), nullable=True),
    sa.Column('picture_m', sa.String(), nullable=True),
    sa.Column('picture_s', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
