"""empty message

Revision ID: e5e5e3cb1073
Revises: f918bfd263ea
Create Date: 2021-06-16 10:15:34.865507

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e5e5e3cb1073"
down_revision = "f918bfd263ea"
branch_labels = None
depends_on = None


def upgrade():
    """1. Remove extra columns."""
    with op.batch_alter_table("users") as batch_op:
        batch_op.drop_column("registered_date")
        batch_op.drop_column("registered_age")
        batch_op.drop_column("cell")
        batch_op.drop_column("portrait_id")
        batch_op.drop_column("street_number")
        batch_op.drop_column("id_value")
        batch_op.drop_column("nat")
        batch_op.drop_column("id_name")
        batch_op.drop_column("md5")
        batch_op.drop_column("date_of_birth")
        batch_op.drop_column("sha256")
        batch_op.drop_column("username")
        batch_op.drop_column("salt")
        batch_op.drop_column("timezone_offset")
        batch_op.drop_column("uuid")
        batch_op.drop_column("title")
        batch_op.drop_column("age")
        batch_op.drop_column("longitude")
        batch_op.drop_column("sha1")
        batch_op.drop_column("timezone_description")
        batch_op.drop_column("password")
        batch_op.drop_column("latitude")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("latitude", sa.VARCHAR(), nullable=True))
    op.add_column("users", sa.Column("password", sa.VARCHAR(), nullable=True))
    op.add_column(
        "users", sa.Column("timezone_description", sa.VARCHAR(), nullable=True)
    )
    op.add_column("users", sa.Column("sha1", sa.VARCHAR(length=40), nullable=True))
    op.add_column("users", sa.Column("longitude", sa.VARCHAR(), nullable=True))
    op.add_column("users", sa.Column("age", sa.SMALLINT(), nullable=True))
    op.add_column("users", sa.Column("title", sa.VARCHAR(), nullable=True))
    op.add_column("users", sa.Column("uuid", sa.VARCHAR(), nullable=True))
    op.add_column("users", sa.Column("timezone_offset", sa.VARCHAR(), nullable=True))
    op.add_column("users", sa.Column("salt", sa.VARCHAR(), nullable=True))
    op.add_column("users", sa.Column("username", sa.VARCHAR(), nullable=True))
    op.add_column("users", sa.Column("sha256", sa.VARCHAR(length=64), nullable=True))
    op.add_column(
        "users", sa.Column("date_of_birth", sa.VARCHAR(length=32), nullable=True)
    )
    op.add_column("users", sa.Column("md5", sa.VARCHAR(length=32), nullable=True))
    op.add_column("users", sa.Column("id_name", sa.VARCHAR(), nullable=True))
    op.add_column("users", sa.Column("nat", sa.VARCHAR(length=8), nullable=True))
    op.add_column("users", sa.Column("id_value", sa.VARCHAR(), nullable=True))
    op.add_column("users", sa.Column("street_number", sa.INTEGER(), nullable=True))
    op.add_column("users", sa.Column("portrait_id", sa.INTEGER(), nullable=True))
    op.add_column("users", sa.Column("cell", sa.VARCHAR(length=32), nullable=True))
    op.add_column("users", sa.Column("registered_age", sa.SMALLINT(), nullable=True))
    op.add_column(
        "users", sa.Column("registered_date", sa.VARCHAR(length=32), nullable=True)
    )
    # ### end Alembic commands ###
